// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJouWw8L8byJVL6DWVnr_66anUXr_E94',
    appId: '1:655431555564:web:edd81ba1448cdb47c448c9',
    messagingSenderId: '655431555564',
    projectId: 'christ-first-note-app',
    authDomain: 'christ-first-note-app.firebaseapp.com',
    storageBucket: 'christ-first-note-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gMs3YUf6ITysTHwi5KqAs6CDZobdzjU',
    appId: '1:655431555564:android:b103edb41fbb6f5fc448c9',
    messagingSenderId: '655431555564',
    projectId: 'christ-first-note-app',
    storageBucket: 'christ-first-note-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6v5XadPBdpDDoqNM5vuAOA3vLX2naeTc',
    appId: '1:655431555564:ios:b156791bab7cade2c448c9',
    messagingSenderId: '655431555564',
    projectId: 'christ-first-note-app',
    storageBucket: 'christ-first-note-app.appspot.com',
    iosClientId: '655431555564-4l9qq103g1tfvvmu9fci6htm0cioffnb.apps.googleusercontent.com',
    iosBundleId: 'com.malouchrist',
  );
}
